name: SofiAI Tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint JS
        run: npm run lint:js
      
      - name: Lint CSS
        run: npm run lint:css
      
      - name: Lint HTML
        run: npm run lint:html
        
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  flask-and-e2e:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: OmegaConf
        run: pip install omegaconf

      - name: Start Flask Server
        run: |
          python app.py &
          sleep(10)
          echo "Flask server started"
      - name: Check Flask server availability
        run: |
          for /l %i in (1,1,10) do (
            timeout /t 5 > nul
            curl -Is http://localhost:5000 | find "HTTP/1.1 200 OK" > nul
            if not errorlevel 1 (
              echo "Flask server is running and available."
              exit /b 0
            )
          )
          echo "Flask server is not running or not available."
          exit /b 1

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          npm run test:cypress


      