name: SofiAI Tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint JS
        run: npm run lint:js
      
      - name: Lint CSS
        run: npm run lint:css
      
      - name: Lint HTML
        run: npm run lint:html
        
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  e2e-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node dependencies
        run: npm install
      
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Run Flask application
        env:
          PORT: ${{ github.event.client_port }}
        run: |
          export FLASK_APP=app.py
          flask run --host=0.0.0.0 --port=$PORT

      - name: Run Cypress tests
        run: npm run test:cypress